# Generated by Django 3.2.12 on 2022-03-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
